### ISSUE TITLE
Missing icon in tabs

### ISSUE THREAD

**Issue by sorxrob** [aaronksaunders/ionic4-vue-tabs#1]
Hi! Thank you for this basic example on how to set things up.

Did you manage to make icons work?

```
<ion-tab-button tab="activity">
    <ion-icon name="contacts"></ion-icon>
    <ion-label>Activity</ion-label>
</ion-tab-button>
```

The ion-icon component isn't displaying anything. If you made it work, can you please share what are the steps? Thanks!

**Comment by aaronksaunders** [comment]
i just ran this code and it works fine, please ensure you are running the exact same versions and 

<img width="505" alt="Screen Shot 2019-07-11 at 8 45 19 AM" src="https://user-images.githubusercontent.com/524953/61051947-52cd3180-a3b8-11e9-88e7-5745d16b1bce.png">

**Comment by sorxrob** [comment]
Yeah you're right. I've used the next version of @ionic/vue. Thank you.
